---
- name: Install SSH
  apt:
    name: openssh-server
    state: present

- name: Configure SSH service
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?X11Forwarding"
      line: "X11Forwarding no"
  notify: restart ssh
